### PR TITLE
fix: Fix rule merging without a match

### LINKED ISSUE #167: mergeWithRules and shortcuts (`loaders` and `use`)
Two questions:  
1. How would one merge `loaders` with `use` using `mergeWithRules`. Is it even possible? Any alternative?
2. The following test fails with `TypeError: Cannot read property 'options' of undefined`.
```ts
    const conf1 = {
      module: {
        rules:[
          {
            "test": "/\\.scss$|\\.sass$/",
            "use": [
              {
                "loader": "sass-loader",
                "options": {
                  "sourceMap": true,
                  "sassOptions": {
                    "precision": 8,
                    "outputStyle": "expanded"
                  }
                }
              }
            ]
          }
        ]
      }
    };
    const conf2 = {
      module: {
        rules:[
          {
            "test": "/\\.scss$|\\.sass$/",
            "exclude": [
              "/node_modules/",
              "/v1/"
            ],
            "loaders": [
              {
                "loader": "sass-resources-loader",
                "options": {
                  "resources": [
                    "src/styles/includes.scss"
                  ]
                }
              }
            ]
          }
        ]
      }
    };

    const mergeRules = {
      module: {
        rules: {
          test: CustomizeRule.Match,
          use: {
            loader: CustomizeRule.Match,
            options: CustomizeRule.Merge,
          },
        },
      },
    }

    expect(mergeWithRules(mergeRules)(conf1, conf2)).toBeTruthy();
```

I'm not sure about that, but I wouldn't expect it to fail. WDYT?

### PR DESCRIPTION
**Pull request by bebraw**
@just-jeb, Do you think there are other cases to cover or would this do? The fix was quite simple.

Closes #167.

### CODE REVIEW

**Comment by just-jeb** [comment]
@bebraw I'm not sure this is valid only for `merge`. What if `options` was array and I'd want to `prepend` it if there is a full match?  
I'd still expect the entries in `use` to be appended and the `options` prepended when there is a match in `loader`.

**Comment by bebraw** [comment]
> I'm not sure this is valid only for merge. What if options was array and I'd want to prepend it if there is a full match?
I'd still expect the entries in use to be appended and the options prepended when there is a match in loader.

Can you open another issue about that and what it should look like? As mentioned earlier, it might need another operator to avoid implicit behavior.

I think I'll merge and publish this one as it's a valid fix and that's a feature.

**Comment by just-jeb** [comment]
Thanks! Well, for my specific use case this fix is enough. I was just thinking about additional use cases that people might face.

**Comment by bebraw** [comment]
@just-jeb Sure, if you have time and you want, feel free to send examples as that helps a lot in thinking about these. 👍

**Pull request merged**
