### PR TITLE
README. Exclude/include explanation

### PR DESCRIPTION
**Pull request by andrewMuntyan**
Was reading [this issue: smart merge does not merge loaders if include is defined](https://github.com/survivejs/webpack-merge/issues/96). Add some explanation to `README.md` about **exclude** and **include** keys in merged configurations. Not sure i've got whole logic, pls let me know if i have not.

### CODE REVIEW

**Comment by bebraw** [comment]
I wonder if we should make the implementation more intuitive and then simplify the explanation. What's your take on this? I don't mind changing.

**Comment by andrewMuntyan** [comment]
it would be great, but i thought it should be in next major version [as you mentioned here ](https://github.com/survivejs/webpack-merge/issues/96#issuecomment-379488252)

**Comment by bebraw** [comment]
@andrewMuntyan Let's go with the API change. Far better long term. I don't mind publishing a new major version.

**Comment by bebraw** [comment]
@andrewMuntyan I might be able to pull it off during the weekend but maybe it's better you give it a go first. There isn't much code and it's **heavily** tested.

**Comment by bebraw** [comment]
I'm dropping support for smart merging in v5 (#135). I believe the utilities included are enough to replace it, though, and there are specific features like wildcards for the customized variant to make up for this change.

**Pull request closed without merging**
